## Widget Brain - Technical Exam
### March 22nd, 2018
### Alex Ram

In [1]:
import os
import numpy as np
import pandas as pd

In [48]:
#my local path to the csv file
path = os.getcwd() + '\\data\\wb-data-science-test\\VesselData.csv'
#covernt the data to a pandas dataframe so it's easy to manipulate
data = pd.read_csv(path, header=0)

In [49]:
#this block helps me visulize the data
data

,eta,ata,atd,vesseldwt,vesseltype,discharge1,load1,discharge2,load2,discharge3,...,load4,stevedorenames,hasnohamis,earliesteta,latesteta,traveltype,previousportid,nextportid,isremarkable,vesselid
0,2017-09-19 00:00:00+00,2017-09-19 00:00:00+00,2017-09-22 00:00:00+00,109290.0,5,0,0,0,0,90173,...,0,Stevedore_104,NaN,2017-09-19 00:00:00+00,2017-09-19 00:00:00+00,ARRIVAL,981,731,f,2242
1,2017-10-02 00:00:00+00,2017-10-02 00:00:00+00,2017-10-03 00:00:00+00,67170.0,3,0,0,0,0,0,...,0,Stevedore_109,NaN,2017-10-02 00:00:00+00,2017-10-02 00:00:00+00,ARRIVAL,19,15,f,5462
2,2017-09-30 00:00:00+00,2017-09-30 00:00:00+00,2017-10-01 00:00:00+00,67737.0,3,0,0,0,0,0,...,0,Stevedore_57,NaN,2017-09-30 00:00:00+00,2017-09-30 00:00:00+00,ARRIVAL,19,19,f,5251
3,2017-10-02 00:00:00+00,2017-10-02 00:00:00+00,2017-10-03 00:00:00+00,43600.0,3,0,0,0,0,0,...,0,Stevedore_57,NaN,2017-10-02 00:00:00+00,2017-10-02 00:00:00+00,ARRIVAL,15,18,f,5268
4,2017-10-02 00:00:00+00,2017-10-02 00:00:00+00,2017-10-02 00:00:00+00,9231.0,3,0,0,0,0,0,...,0,Stevedore_98,NaN,2017-10-02 00:00:00+00,2017-10-02 00:00:00+00,ARRIVAL,74,27,f,5504
5,2017-09-29 00:00:00+00,2017-09-29 00:00:00+00,2017-10-01 00:00:00+00,74518.0,2,72741,0,0,0,0,...,0,Stevedore_67,NaN,2017-09-29 00:00:00+00,2017-09-29 00:00:00+00,ARRIVAL,981,981,f,7242
6,2017-10-02 00:00:00+00,2017-10-01 00:00:00+00,2017-10-02 00:00:00+00,8620.0,3,0,0,0,0,0,...,0,"Stevedore_109,Stevedore_57,Stevedore_64",NaN,2017-10-01 00:00:00+00,2017-10-02 00:00:00+00,SHIFT,18,766,f,4756
7,2017-10-15 00:00:00+00,2017-10-16 00:00:00+00,2017-10-18 00:00:00+00,46428.0,3,0,0,0,0,0,...,0,Stevedore_102,NaN,2017-10-15 00:00:00+00,2017-10-15 00:00:00+00,ARRIVAL,260,95,f,1716
8,2017-11-06 00:00:00+00,2017-11-06 00:00:00+00,2017-11-07 00:00:00+00,17069.0,5,0,0,0,0,14044,...,0,Stevedore_35,NaN,2017-11-05 00:00:00+00,2017-11-06 00:00:00+00,ARRIVAL,36,286,f,2542
9,2017-10-05 00:00:00+00,2017-10-06 00:00:00+00,2017-10-07 00:00:00+00,67170.0,3,0,0,0,0,0,...,0,Stevedore_57,NaN,2017-10-05 00:00:00+00,2017-10-05 00:00:00+00,ARRIVAL,73,19,f,5757
10,2017-10-12 00:00:00+00,2017-10-15 00:00:00+00,2017-10-16 00:00:00+00,64989.0,3,0,0,0,0,0,...,0,Stevedore_57,NaN,2017-10-12 00:00:00+00,2017-10-12 00:00:00+00,ARRIVAL,73,19,f,5797
11,2017-10-20 00:00:00+00,2017-10-22 00:00:00+00,2017-10-22 00:00:00+00,12306.0,3,0,0,0,0,0,...,0,Stevedore_45,NaN,2017-10-20 00:00:00+00,2017-10-20 00:00:00+00,ARRIVAL,1014,18,f,5011
12,2017-09-05 00:00:00+00,2017-09-05 00:00:00+00,2017-09-08 00:00:00+00,139335.0,3,0,0,0,0,0,...,0,Stevedore_57,NaN,2017-09-05 00:00:00+00,2017-09-05 00:00:00+00,ARRIVAL,879,19,f,5399
13,2017-09-25 00:00:00+00,2017-09-25 00:00:00+00,2017-09-26 00:00:00+00,3002.0,3,0,0,0,0,0,...,0,Stevedore_87,NaN,2017-09-25 00:00:00+00,2017-09-25 00:00:00+00,ARRIVAL,31,18,f,1793
14,2017-09-17 00:00:00+00,2017-09-17 00:00:00+00,2017-09-17 00:00:00+00,9344.0,3,0,0,0,0,0,...,0,Stevedore_98,NaN,2017-09-17 00:00:00+00,2017-09-17 00:00:00+00,ARRIVAL,18,35,f,5237
15,2017-10-04 00:00:00+00,2017-10-04 00:00:00+00,2017-10-05 00:00:00+00,9231.0,3,0,0,0,0,0,...,0,Stevedore_98,NaN,2017-10-04 00:00:00+00,2017-10-04 00:00:00+00,ARRIVAL,74,74,f,5504
16,2017-09-14 00:00:00+00,2017-09-14 00:00:00+00,2017-09-15 00:00:00+00,9322.0,3,0,0,0,0,0,...,0,Stevedore_98,NaN,2017-09-14 00:00:00+00,2017-09-14 00:00:00+00,ARRIVAL,14,1000,f,4832
17,2017-09-30 00:00:00+00,2017-09-30 00:00:00+00,2017-10-01 00:00:00+00,13965.0,3,0,0,0,0,0,...,0,Stevedore_98,NaN,2017-09-30 00:00:00+00,2017-09-30 00:00:00+00,ARRIVAL,14,87,f,5076
18,2017-10-04 00:00:00+00,2017-10-04 00:00:00+00,2017-10-04 00:00:00+00,9350.0,3,0,0,0,0,0,...,0,Stevedore_98,NaN,2017-10-04 00:00:00+00,2017-10-04 00:00:00+00,ARRIVAL,27,27,f,5503
19,2017-11-09 00:00:00+00,2017-11-09 00:00:00+00,2017-11-10 00:00:00+00,152343.0,3,0,0,0,0,0,...,0,Stevedore_57,NaN,2017-11-09 00:00:00+00,2017-11-09 00:00:00+00,ARRIVAL,1040,766,f,4881
20,2017-10-13 00:00:00+00,2017-10-13 00:00:00+00,2017-10-13 00:00:00+00,9741.0,3,0,0,0,0,0,...,0,Stevedore_92,NaN,2017-10-13 00:00:00+00,2017-10-13 00:00:00+00,ARRIVAL,14,14,f,4596
21,2017-10-04 00:00:00+00,2017-10-04 00:00:00+00,2017-10-06 00:00:00+00,114106.0,3,0,0,0,0,0,...,0,Stevedore_57,NaN,2017-10-04 00:00:00+00,2017-10-04 00:00:00+00,ARRIVAL,73,18,f,7246
22,2017-10-16 00:00:00+00,2017-10-16 00:00:00+00,2017-10-17 00:00:00+00,60200.0,3,0,0,0,0,0,...,0,Stevedore_57,NaN,2017-10-14 00:00:00+00,2017-10-16 00:00:00+00,ARRIVAL,766,18,f,5615
23,2017-09-12 00:00:00+00,2017-09-12 00:00:00+00,2017-09-13 00:00:00+00,7133.0,3,0,4188,0,0,0,...,0,Stevedore_77,NaN,2017-09-12 00:00:00+00,2017-09-12 00:00:00+00,ARRIVAL,45,1037,f,894
24,2017-09-09 00:00:00+00,2017-09-08 00:00:00+00,2017-09-10 00:00:00+00,2300.0,3,0,0,0,0,0,...,0,"Stevedore_89,Stevedore_74",NaN,2017-09-08 00:00:00+00,2017-09-09 00:00:00+00,SHIFT,5,126,f,1169
25,2017-09-10 00:00:00+00,2017-09-09 00:00:00+00,2017-09-10 00:00:00+00,2500.0,3,0,0,0,0,0,...,0,Stevedore_74,NaN,2017-09-09 00:00:00+00,2017-09-10 00:00:00+00,SHIFT,3,995,f,1831
26,2017-09-19 00:00:00+00,2017-09-19 00:00:00+00,2017-09-22 00:00:00+00,32017.0,2,0,0,0,0,0,...,0,Stevedore_74,NaN,2017-09-19 00:00:00+00,2017-09-19 00:00:00+00,ARRIVAL,307,59,f,7143
27,2017-10-05 00:00:00+00,2017-10-05 00:00:00+00,2017-10-07 00:00:00+00,158070.0,5,0,0,0,0,131231,...,0,Stevedore_83,NaN,2017-10-05 00:00:00+00,2017-10-05 00:00:00+00,ARRIVAL,1291,1156,f,7144
28,2017-11-02 00:00:00+00,2017-11-05 00:00:00+00,2017-11-06 00:00:00+00,23295.0,3,0,0,0,0,0,...,0,Stevedore_110,NaN,2017-11-02 00:00:00+00,2017-11-02 00:00:00+00,ARRIVAL,31,1851,f,7146
29,2017-10-17 00:00:00+00,2017-10-17 00:00:00+00,2017-10-19 00:00:00+00,104525.0,3,0,0,0,0,0,...,0,Stevedore_57,NaN,2017-10-17 00:00:00+00,2017-10-17 00:00:00+00,ARRIVAL,1114,19,f,5759
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8178,2017-11-10 00:00:00+00,2017-11-10 00:00:00+00,2017-11-12 00:00:00+00,152344.0,3,0,0,0,0,0,...,0,Stevedore_57,NaN,2017-11-10 00:00:00+00,2017-11-10 00:00:00+00,ARRIVAL,19,1040,f,4874
8179,2017-11-13 00:00:00+00,2017-11-12 00:00:00+00,2017-11-14 00:00:00+00,14483.0,3,0,0,0,0,0,...,0,"Stevedore_64,Stevedore_109,Stevedore_57,Steved...",NaN,2017-11-12 00:00:00+00,2017-11-13 00:00:00+00,SHIFT,95,988,f,4890
8180,2017-11-04 00:00:00+00,2017-11-02 00:00:00+00,2017-11-05 00:00:00+00,24700.0,3,0,0,0,0,0,...,0,"Stevedore_99,Stevedore_109,Stevedore_64,Steved...",NaN,2017-11-03 00:00:00+00,2017-11-05 00:00:00+00,SHIFT,981,1000,f,5498
8181,2017-11-11 00:00:00+00,2017-11-10 00:00:00+00,2017-11-12 00:00:00+00,11257.0,3,0,0,0,0,0,...,0,"Stevedore_109,Stevedore_89,Stevedore_64,Steved...",NaN,2017-11-10 00:00:00+00,2017-11-11 00:00:00+00,SHIFT,15,79,f,4747
8182,2017-11-12 00:00:00+00,2017-11-11 00:00:00+00,2017-11-12 00:00:00+00,9654.0,3,0,0,0,0,0,...,0,"Stevedore_109,Stevedore_57,Stevedore_99,Steved...",NaN,2017-11-11 00:00:00+00,2017-11-12 00:00:00+00,SHIFT,101,102,f,4843
8183,2017-11-06 00:00:00+00,2017-11-05 00:00:00+00,2017-11-07 00:00:00+00,12850.0,3,0,0,0,0,0,...,0,"Stevedore_99,Stevedore_110,Stevedore_57,Steved...",NaN,2017-11-03 00:00:00+00,2017-11-07 00:00:00+00,SHIFT,72,988,f,6779
8184,2017-10-30 00:00:00+00,2017-11-04 00:00:00+00,2017-11-05 00:00:00+00,150936.0,3,0,0,0,0,0,...,0,Stevedore_99,NaN,2017-10-30 00:00:00+00,2017-10-30 00:00:00+00,ARRIVAL,15,19,f,4867
8185,2017-10-09 00:00:00+00,2017-10-04 00:00:00+00,2017-10-12 00:00:00+00,32315.0,5,0,0,0,0,0,...,0,"Stevedore_113,Stevedore_112,Stevedore_104,Stev...",NaN,2017-10-04 00:00:00+00,2017-10-11 00:00:00+00,SHIFT,287,343,f,3897
8186,2017-10-04 00:00:00+00,2017-10-03 00:00:00+00,2017-10-05 00:00:00+00,4993.0,5,0,0,0,0,0,...,3800,Stevedore_104,NaN,2017-10-03 00:00:00+00,2017-10-04 00:00:00+00,ARRIVAL,1880,165,f,3584
8187,2017-10-18 00:00:00+00,2017-10-17 00:00:00+00,2017-10-20 00:00:00+00,197059.0,3,0,0,0,0,0,...,0,Stevedore_99,NaN,2017-10-18 00:00:00+00,2017-10-18 00:00:00+00,ARRIVAL,908,15,f,6845
8188,2017-11-01 00:00:00+00,2017-11-01 00:00:00+00,2017-11-03 00:00:00+00,25432.0,5,0,0,0,0,0,...,0,Stevedore_104,NaN,2017-11-01 00:00:00+00,2017-11-01 00:00:00+00,ARRIVAL,71,981,f,2970
8189,2017-11-01 00:00:00+00,2017-10-28 00:00:00+00,2017-11-03 00:00:00+00,37632.0,5,0,0,0,0,0,...,0,"Stevedore_75,Stevedore_89",NaN,2017-10-28 00:00:00+00,2017-11-01 00:00:00+00,SHIFT,46,5,f,4380
8190,2017-11-01 00:00:00+00,2017-10-30 00:00:00+00,2017-11-02 00:00:00+00,10745.0,5,0,0,0,0,0,...,0,"Stevedore_104,Stevedore_115",NaN,2017-10-30 00:00:00+00,2017-11-01 00:00:00+00,SHIFT,665,1914,f,4144
8191,2017-11-01 00:00:00+00,2017-10-25 00:00:00+00,2017-11-02 00:00:00+00,4993.0,5,0,0,0,0,0,...,4206,"Stevedore_75,Stevedore_65",NaN,2017-10-25 00:00:00+00,2017-11-01 00:00:00+00,SHIFT,19,712,f,3584
8192,2017-11-02 00:00:00+00,2017-11-01 00:00:00+00,2017-11-03 00:00:00+00,158583.0,5,0,0,0,0,139431,...,0,"Stevedore_84,Stevedore_83",NaN,2017-10-25 00:00:00+00,2017-11-02 00:00:00+00,SHIFT,619,14,f,2375
8193,2017-10-22 00:00:00+00,2017-10-21 00:00:00+00,2017-10-23 00:00:00+00,37395.0,5,0,0,0,0,0,...,0,"Stevedore_115,Stevedore_103",NaN,2017-10-21 00:00:00+00,2017-10-22 00:00:00+00,SHIFT,343,19,f,4114
8194,2017-11-01 00:00:00+00,2017-11-01 00:00:00+00,2017-11-05 00:00:00+00,37296.0,5,0,0,0,0,0,...,0,Stevedore_41,NaN,2017-11-01 00:00:00+00,2017-11-01 00:00:00+00,ARRIVAL,257,575,f,3427
8195,2017-11-01 00:00:00+00,2017-11-01 00:00:00+00,2017-11-01 00:00:00+00,13439.0,3,0,0,0,0,0,...,0,Stevedore_46,NaN,2017-11-01 00:00:00+00,2017-11-01 00:00:00+00,ARRIVAL,666,32,f,4598
8196,2017-11-15 00:00:00+00,2017-11-15 00:00:00+00,2017-11-15 00:00:00+00,5297.0,5,0,0,0,0,0,...,0,Stevedore_104,NaN,2017-11-15 00:00:00+00,2017-11-15 00:00:00+00,ARRIVAL,1032,18,f,3863
8197,2017-11-07 00:00:00+00,2017-11-07 00:00:00+00,2017-11-07 00:00:00+00,68142.0,3,0,0,0,0,0,...,0,Stevedore_57,NaN,2017-11-06 00:00:00+00,2017-11-07 00:00:00+00,ARRIVAL,18,19,f,5256
8198,2017-11-09 00:00:00+00,2017-11-09 00:00:00+00,2017-11-09 00:00:00+00,6374.0,3,0,0,0,0,0,...,0,Stevedore_46,NaN,2017-11-09 00:00:00+00,2017-11-09 00:00:00+00,ARRIVAL,32,32,f,4607
8199,2017-11-11 00:00:00+00,2017-11-11 00:00:00+00,2017-11-11 00:00:00+00,13439.0,3,0,0,0,0,0,...,0,Stevedore_46,NaN,2017-11-11 00:00:00+00,2017-11-11 00:00:00+00,ARRIVAL,666,32,f,4598
8200,2017-11-10 00:00:00+00,2017-11-09 00:00:00+00,2017-11-11 00:00:00+00,7193.0,3,0,0,0,0,0,...,0,"Stevedore_43,Stevedore_34",NaN,2017-11-09 00:00:00+00,2017-11-10 00:00:00+00,SHIFT,767,767,f,4592
8201,2017-11-03 00:00:00+00,2017-11-03 00:00:00+00,2017-11-03 00:00:00+00,7261.0,3,0,0,0,0,0,...,0,Stevedore_105,NaN,2017-11-03 00:00:00+00,2017-11-03 00:00:00+00,ARRIVAL,666,666,f,4632
8202,2017-11-03 00:00:00+00,2017-11-01 00:00:00+00,2017-11-05 00:00:00+00,15952.0,3,0,0,0,0,0,...,0,"Stevedore_45,Stevedore_64,Stevedore_57,Stevedo...",NaN,2017-10-26 00:00:00+00,2017-11-04 00:00:00+00,SHIFT,19,1000,f,4861
8203,2017-11-03 00:00:00+00,2017-11-03 00:00:00+00,2017-11-04 00:00:00+00,9587.0,3,0,0,0,0,0,...,0,Stevedore_64,NaN,2017-11-02 00:00:00+00,2017-11-03 00:00:00+00,ARRIVAL,5,19,f,5681
8204,2017-11-04 00:00:00+00,2017-11-04 00:00:00+00,2017-11-06 00:00:00+00,9654.0,3,0,0,0,0,0,...,0,"Stevedore_110,Stevedore_57,Stevedore_99,Steved...",NaN,2017-11-04 00:00:00+00,2017-11-05 00:00:00+00,SHIFT,391,102,f,4843
8205,2017-11-08 00:00:00+00,2017-11-07 00:00:00+00,2017-11-11 00:00:00+00,4726.0,5,0,0,0,0,0,...,3051,"Stevedore_89,Stevedore_79,Stevedore_75,Stevedo...",NaN,2017-11-07 00:00:00+00,2017-11-10 00:00:00+00,SHIFT,1043,19,f,3115
8206,2017-11-10 00:00:00+00,2017-11-10 00:00:00+00,2017-11-10 00:00:00+00,13320.0,3,0,0,0,0,0,...,0,Stevedore_46,NaN,2017-11-10 00:00:00+00,2017-11-10 00:00:00+00,ARRIVAL,54,71,f,4623
8207,2017-11-10 00:00:00+00,2017-11-08 00:00:00+00,2017-11-10 00:00:00+00,11020.0,3,0,0,0,0,0,...,0,"Stevedore_28,Stevedore_99,Stevedore_57,Stevedo...",NaN,2017-11-08 00:00:00+00,2017-11-10 00:00:00+00,SHIFT,1060,14,f,4785

In [52]:
# To start, since I have a time limit, I'm going to da a simple monthly prediction using amount of each type 
#by coverting the ata's to a set i know all the ships recorded arived between 2017-04-15 and 2017-11-15
atas = set(data['ata'])
#we now know there are 7 months total
load1_avg = data['load1'].sum()/7
load2_avg = data['load2'].sum()/7
load3_avg = data['load3'].sum()/7
load4_avg = data['load4'].sum()/7
discharge1_avg = data['discharge1'].sum()/7
discharge2_avg = data['discharge2'].sum()/7
discharge3_avg = data['discharge3'].sum()/7
discharge4_avg = data['discharge4'].sum()/7

In [56]:
#now i have a monthly average of how much is loaded and discharged of each type
print('Monthly average:')
print('load 1: ' , load1_avg)
print('load 2: ' , load2_avg)
print('load 3: ' , load3_avg)
print('load 4: ' , load4_avg)
print('discharge 1: ' , discharge1_avg)
print('discharge 2: ' , discharge2_avg)
print('discharge 3: ' , discharge3_avg)
print('discharge 4: ' , discharge4_avg)

Monthly average:
load 1:  71238.85714285714
load 2:  22733.285714285714
load 3:  52467.28571428572
load 4:  1769465.142857143
discharge 1:  2031729.5714285714
discharge 2:  1370382.142857143
discharge 3:  5618178.857142857
discharge 4:  2134997.4285714286

In [127]:
#obviously this is not the optimal solution. You want me to use learning algorithms.
#my system, after being trained, is going to take in some information about the vessle and predict 
#the load and discharge value for each type.
#by knowing which vessles arrived each month, these values can be summed up to predict the total monthly transshipments.

#X represents the vesseldwt and vesseltype which i thought were important characteristics about the ship
X = data.iloc[:,3:5]

try:
    #insert ones column in order to do certain vectorized solutions
    X.insert(0, 'Ones', 1)
except:
    pass
#normalize values
X = (X - X.mean()) / X.std() 
#the output is just the load of type one, and if succesful I can get a correlation between all types
y = data.iloc[:,5:6]
y = (y - y.mean()) / y.std() 
X = np.matrix(X.values)
y = np.matrix(y.values)


#i had help from this tutorial http://www.johnwittenauer.net/machine-learning-exercises-in-python-part-1/

theta = np.matrix(np.zeros((1,3))) 

alpha = 0.01
iters = 1000

def calcLinearRegressionMultiCost(X, y, theta):
    return np.sum(np.power(((X * theta.T) - y), 2)) / (2 * len(X))
    
def LinearRegressionMultiGradientDescent(X, y, theta, alpha, iters):
    temp = theta.copy()
    param = theta[0].shape[1]
    cost = np.zeros(iters)
    
    for i in range(iters):
        error = (X * theta.T) - y
        for j in range(param):
            temp[0,j] = theta[0,j] - ((alpha / len(X)) * np.sum(np.multiply(error, X[:,j])))
            
        theta = temp
        cost[i] = calcLinearRegressionMultiCost(X, y, theta)
        
    return theta, cost

g, cost = LinearRegressionMultiGradientDescent(X, y, theta, alpha, iters)

In [ ]:
# I was unable to get the linear regresion algorithm to work in the time given. If I were able to I would add more parameters
# about the ship.